Check on bxc storage

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -29,6 +29,12 @@ jobs:
           CATALINA_OPTS: "-Djava.awt.headless=true -server -Xms512m -Xmx1024m -XX:NewSize=256m -XX:MaxNewSize=256m -Dfcrepo.external.content.allowed=/config/allowed_external_paths.txt"
 
     steps:
+    - name: Change permissions of /tmp/boxc_test_storage
+      run: sudo chmod 2777 /tmp/boxc_test_storage
+    - name: List tmp
+      run: ls -la /tmp/
+    - name: List tmp/bxc_test_storage
+      run: ls -la /tmp/boxc_test_storage
     - name: Checkout repository
       uses: actions/checkout@v2
     - name: Get Container ID of fedora service
@@ -38,6 +44,10 @@ jobs:
         echo "CONTAINER_ID=$CONTAINER_ID" >> $GITHUB_ENV
     - name: Restart fedora now that the repository has been checked out so config files are available
       run: docker restart ${{ env.CONTAINER_ID }}
+    - name: List tmp on fedora
+      run: docker exec ${{ env.CONTAINER_ID }} ls -la /tmp/
+    - name: List tmp/bxc on fedora
+      run: docker exec ${{ env.CONTAINER_ID }} ls -la /tmp/boxc_test_storage
     - name: Checkout submodules
       run: git submodule update --init --recursive
     - name: Set up JDK 11
@@ -50,42 +60,42 @@ jobs:
         path: ~/.m2
         key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
         restore-keys: ${{ runner.os }}-m2
-#    - name: Wait for fedora to become available
-#      run: |
-#        URL="http://localhost:48085/fcrepo/rest"
-#        timeout=$(( $(date '+%s') + 120 ))  # Set timeout to 2 minutes from now
-#        while true; do
-#          response=$(curl -s -o /dev/null -w "%{http_code}" $URL)
-#          if [ $response -eq 200 ]; then
-#            echo "URL is available! $response"
-#            break
-#          elif [ $(date '+%s') -gt $timeout ]; then
-#            echo "Timeout reached. URL did not become available within 2 minutes."
-#            exit 1
-#          else
-#            echo "URL is not yet available, waiting... $response"
-#            sleep 10  # Adjust the interval (in seconds) between retries
-#          fi
-#        done
+##    - name: Wait for fedora to become available
+##      run: |
+##        URL="http://localhost:48085/fcrepo/rest"
+##        timeout=$(( $(date '+%s') + 120 ))  # Set timeout to 2 minutes from now
+##        while true; do
+##          response=$(curl -s -o /dev/null -w "%{http_code}" $URL)
+##          if [ $response -eq 200 ]; then
+##            echo "URL is available! $response"
+##            break
+##          elif [ $(date '+%s') -gt $timeout ]; then
+##            echo "Timeout reached. URL did not become available within 2 minutes."
+##            exit 1
+##          else
+##            echo "URL is not yet available, waiting... $response"
+##            sleep 10  # Adjust the interval (in seconds) between retries
+##          fi
+##        done
     - name: Build with Maven
       run: mvn -B -U -pl '!integration' clean install -DskipTests
-#    - name: Set up nodejs
-#      uses: actions/setup-node@v2
-#      with:
-#        node-version: '16'
-#    - name: Cache npm modules
-#      uses: actions/cache@v2
-#      with:
-#        path: ~/.npm
-#        key: v1-npm-deps-${{ hashFiles('**/package-lock.json') }}
-#        restore-keys: v1-npm-deps-
-
-#    - run: npm --prefix static/js/vue-cdr-access install
-#    - run: npm --prefix static/js/admin/vue-permissions-editor install
+##    - name: Set up nodejs
+##      uses: actions/setup-node@v2
+##      with:
+##        node-version: '16'
+##    - name: Cache npm modules
+##      uses: actions/cache@v2
+##      with:
+##        path: ~/.npm
+##        key: v1-npm-deps-${{ hashFiles('**/package-lock.json') }}
+##        restore-keys: v1-npm-deps-
 #
-#    - run: npm install -g jest-cli@29.0.3
-#    - run: npm --prefix static/js/vue-cdr-access run test
-#    - run: npm --prefix static/js/admin/vue-permissions-editor run test
+##    - run: npm --prefix static/js/vue-cdr-access install
+##    - run: npm --prefix static/js/admin/vue-permissions-editor install
+##
+##    - run: npm install -g jest-cli@29.0.3
+##    - run: npm --prefix static/js/vue-cdr-access run test
+##    - run: npm --prefix static/js/admin/vue-permissions-editor run test
 
     - name: Report to CodeClimate
       uses: paambaati/codeclimate-action@v3.0.0
@@ -99,6 +109,13 @@ jobs:
           ${{github.workspace}}/**/target/site/jacoco-it/jacoco.xml:jacoco
           ${{github.workspace}}/static/js/vue-cdr-access/coverage/lcov.info:lcov
           ${{github.workspace}}/static/js/admin/vue-permissions-editor/coverage/lcov.info:lcov
+
+    - name: List tmp/bxc_test_storage final
+      if: always()
+      run: ls -la /tmp/boxc_test_storage
+    - name: List tmp/bxc on fedora final
+      if: always()
+      run: docker exec ${{ env.CONTAINER_ID }} ls -la /tmp/boxc_test_storage
 
     - name: View fedora service logs
       if: always()
